// Generated by CoffeeScript 1.6.2
(function() {
  var removeDisabled, txtAnimation;

  $(document).ready(function() {
    $('.scene').click(function() {
      if (!$(this).hasClass("disabled")) {
        $(this).addClass("disabled");
        DV.next();
        hideArrows();
        removeDisabled("end_scene");
        txtAnimation();
        return changePin(1);
      }
    });
    $('.reset').click(function() {
      DV.restart();
      hideArrows();
      $(this).addClass("disabled");
      removeDisabled("scene");
      txtAnimation();
      return changePin(1);
    });
    $('.play').click(function() {
      DV.play();
      return $(this).parent().hide();
    });
    return $('.map_4').click(function() {
      DV.play();
      return false;
    });
  });

  txtAnimation = function() {
    return $('.scene_trigger').removeClass("fadeInDown").addClass("fadeOutUp").one("webkitAnimationEnd animationend", function() {});
  };

  removeDisabled = function(obj) {
    return $('.' + obj + '').removeClass("disabled");
  };

}).call(this);
