// Generated by CoffeeScript 1.6.2
(function() {
  var HedgehogAnalyticsData, log;

  HedgehogAnalyticsData = (function() {
    function HedgehogAnalyticsData(enabled) {
      this.enabled = enabled;
      this.send();
    }

    HedgehogAnalyticsData.prototype.build = function(hedgehogs_array) {
      if (hedgehogs_array !== void 0) {
        this.category = 'hedgehog-interactive-video-' + hedgehogs_array[0];
        this.identifier = hedgehogs_array[1];
      }
      return ['_trackEvent', this.category, 'click', this.identifier];
    };

    HedgehogAnalyticsData.prototype.send = function(hedgehogs_array) {
      if (this.enabled) {
        _gaq.push(this.build(hedgehogs_array));
      }
    };

    return HedgehogAnalyticsData;

  })();

  log = function(message) {
    if (typeof console === 'object') {
      return console.log(message);
    } else {
      return null;
    }
  };

  $(document).ready(function() {
    var gaEnabled;

    gaEnabled = typeof _gaq === 'object' ? true : false;
    window.HedgehogGAData = new HedgehogAnalyticsData(gaEnabled);
    link_list();
    link_trigger();
    $('.mappings').on('click', activeMap.Element, function() {
      var mainVid, tracker_tag;

      mainVid = 1;
      DV.start_section(activeMap.Begin);
      tracker_tag = $(activeMap.Element).attr('data-tracking');
      return HedgehogGAData.send(["mapping", tracker_tag]);
    });
    $('.play').click(function() {
      DV.play();
      return $(this).parent().hide();
    });
    $('.btn-danger').click(function() {
      return DV.pause();
    });
    $('.play2').click(function() {
      return DV.play();
    });
  });

}).call(this);
