// Generated by CoffeeScript 1.6.2
(function() {
  var changePin, hideArrows, playTab, removeDisabled, txtAnimation;

  $(document).ready(function() {
    var current_tab, i, iheight, static_current_tab, vheight;

    $('.static_trigger').click(function() {
      $('.video_wrapper').removeClass('inactive').show().addClass('activated');
      $('.static_wrapper').removeClass('activated').hide().addClass('inactive');
      return setInterval(playTab, 200);
    });
    $('.scene').click(function() {
      if (!$(this).hasClass("disabled")) {
        $(this).addClass("disabled");
        DV.next();
        hideArrows();
        removeDisabled("end_scene");
        txtAnimation();
        return changePin(1);
      }
    });
    $('.reset').click(function() {
      DV.restart();
      hideArrows();
      $(this).addClass("disabled");
      removeDisabled("scene");
      txtAnimation();
      return changePin(1);
    });
    current_tab = $('.tab_trigger').parent().parent().index();
    $('li.act-' + current_tab).click(function() {
      return setInterval(playTab, 200);
    });
    static_current_tab = $('.static_tab_trigger').parent().parent().index();
    $('li.act-' + static_current_tab).click(function() {
      $('.static_wrapper').removeClass('inactive').show().addClass('activated');
      $('.video_wrapper').removeClass('activated').hide().addClass('inactive');
      return $('#pins').hide().addClass('inactive');
    });
    $(document).on("click", ".icon-chevron-left", function() {
      DV.prev_scene();
      hideArrows();
      txtAnimation();
      removeDisabled("scene");
      return changePin(0);
    });
    $(document).on("click", ".icon-chevron-right", function() {
      DV.next_scene();
      hideArrows();
      txtAnimation();
      removeDisabled("scene");
      return changePin(1);
    });
    $(document).on("click", ".icon-circle", function() {
      var pinNumber;

      pinNumber = $(this).index();
      $('.active-pill').removeClass('active-pill');
      $(this).addClass('active-pill');
      removeDisabled("scene");
      txtAnimation();
      DV.select_scene(pinNumber);
      return hideArrows();
    });
    if (lbegin.length === lend_value.length) {
      i = 0;
      while (i < lbegin.length) {
        $('#pins').append('<i class="icon-circle"></i>');
        i++;
      }
      if (lbegin.length > 1) {
        $('.video_wrapper').prepend('<i class="icon-chevron-left"></i>').append('<i class="icon-chevron-right"></i>');
        vheight = $('.video_wrapper').height();
        iheight = vheight / 2;
        $('.video_wrapper i').css("top", iheight - 15);
      }
    }
    return $('#pins').find('.icon-circle:first-child').addClass('active-pill');
  });

  changePin = function(direction) {
    var active;

    active = $(".active-pill").removeClass("active-pill");
    if (direction === 1) {
      if (active.next() && active.next().length) {
        return active.next().addClass("active-pill");
      } else {
        return active.siblings(":first").addClass("active-pill");
      }
    } else {
      if (active.prev() && active.prev().length) {
        return active.prev().addClass("active-pill");
      } else {
        return active.siblings(":first").addClass("active-pill");
      }
    }
  };

  hideArrows = function() {
    if (scene === 0) {
      $('.icon-chevron-left').hide();
      return $('.icon-chevron-right').show();
    } else if (scene === 3) {
      $('.icon-chevron-right').hide();
      return $('.icon-chevron-left').show();
    } else {
      $('.icon-chevron-left').show();
      return $('.icon-chevron-right').show();
    }
  };

  playTab = function() {
    if (vidReady === 1) {
      DV.play();
      hideArrows();
      txtAnimation();
      $('#pins').removeClass('inactive').show().addClass('activated');
      return vidReady++;
    } else {
      return false;
    }
  };

  txtAnimation = function() {
    return $('.scene_trigger').removeClass("fadeInDown").addClass("fadeOutUp").one("webkitAnimationEnd animationend", function() {});
  };

  removeDisabled = function(obj) {
    return $('.' + obj + '').removeClass("disabled");
  };

}).call(this);
